-- ============================================================
-- Replace the induction topics with the 18-topic safety-first
-- structure (14 safety, 3 security, 3 general compliance).
-- Run this in Supabase SQL Editor. Safe to re-run.
-- ============================================================

-- Remove all existing English topics (including the old 13-topic set)
delete from induction_topics where language = 'en';

insert into induction_topics (topic_key, language, sort_order, title, body) values
('welcome', 'en', 1, 'Welcome & Purpose of This Induction', 'This induction ensures that everyone deploying on a Miraj Media assignment — whether as event safety, security, or technical personnel — understands the standards, procedures, and legal expectations that apply before setting foot on site. Completing this induction is mandatory for every deployment and must be refreshed for each new engagement or region. All personnel represent Miraj Media and its client at all times, on and off duty, for the duration of the assignment. You are expected to act with honesty, courtesy, and professionalism toward colleagues, clients, talent, media personnel, and the public. Discrimination, harassment, intimidation, or abusive language will not be tolerated and may result in immediate removal from site and termination of the assignment.'),
('ppe', 'en', 2, 'Personal Protective Equipment (PPE) & Uniform Standards', 'The correct uniform and accreditation must be worn visibly at all times while on duty. Where the risk assessment for a specific site requires additional PPE — such as hi-vis, hearing protection, or footwear suited to the venue — this will be issued and is mandatory in those designated areas. Damaged or missing PPE must be reported to your supervisor before starting work, not after.'),
('manual_handling', 'en', 3, 'Manual Handling & Lifting Techniques', 'Incorrect lifting is one of the most common causes of injury on event build and breakdown. Assess the load before you lift it — if it is heavy, awkward, or you are unsure, get help or use mechanical aids such as trolleys or hand pallet jacks rather than lifting alone. When lifting is unavoidable, keep the load close to your body, bend at the knees rather than the back, and keep your back straight. Never twist while carrying a load — move your feet instead. Report any back or muscle strain to your supervisor immediately, however minor it feels at the time.'),
('working_at_height', 'en', 4, 'Working at Height, Ladders & Rigging Safety', 'Any work above ground level — including on ladders, scaffolding, truss, or rigging platforms — carries a fall risk and must only be carried out by personnel authorised and trained for that specific task. Ladders must be inspected before use, placed on stable, level ground, and never used as a substitute for proper access equipment on a prolonged task. Rigging, trussing, and suspended loads must only be handled by qualified riggers under a documented rigging plan — no one else may work beneath a suspended load or an active rigging point. Fall-arrest equipment, where required by the site risk assessment, must be worn correctly and inspected before each use.'),
('electrical_safety', 'en', 5, 'Electrical Safety & Temporary Power', 'Event sites commonly run on temporary power distribution, generators, and long cable runs — all of which carry serious electrical and trip hazards if not managed correctly. Only qualified, authorised electricians may connect, alter, or repair any electrical installation, distribution board, or generator on site. Never use damaged cables, connectors, or equipment — tag it and report it immediately instead. Cables crossing walkways must be properly ramped or covered, not left exposed. Water and electricity must be kept apart at all times, particularly in outdoor and Gulf climate conditions where sudden weather changes are common.'),
('slips_trips_falls', 'en', 6, 'Slips, Trips & Falls Prevention', 'Slips, trips, and falls are among the most frequent incidents on event sites due to cabling, uneven temporary flooring, staging edges, and fast-changing build environments. Keep walkways clear of tools, cable, and debris at all times, and report any spill, loose flooring, or trip hazard immediately rather than stepping around it and leaving it for the next person. Staging and platform edges without permanent guarding must be clearly marked, and personnel must stay alert near unguarded edges, particularly during low-light load-in and load-out periods.'),
('vehicle_loading', 'en', 7, 'Vehicle, Forklift & Loading Bay Safety', 'Loading bays and vehicle access routes are high-risk areas where pedestrians and moving vehicles or forklifts share space, often under time pressure. Pedestrians must use designated walkways where provided and must never assume a reversing vehicle or forklift operator has seen them — always make eye contact with the driver before crossing a vehicle path. Only trained and certified personnel may operate a forklift or other powered material-handling equipment. Loading bay doors, ramps, and dock levellers must be treated as active hazard zones at all times during load-in and load-out.'),
('heat_wellbeing', 'en', 8, 'Heat Stress, Hydration & Personal Wellbeing', 'Deployments across the Gulf region can involve extreme heat and humidity, particularly for outdoor and daytime assignments. Drink water regularly throughout your shift, even if you do not feel thirsty, and inform your supervisor immediately if you or a colleague shows signs of heat exhaustion — including dizziness, nausea, confusion, or stopping sweating. Rest breaks in shaded or cooled areas will be provided on longer deployments and must be taken as scheduled, not skipped.'),
('first_aid', 'en', 9, 'First Aid & Medical Emergency Response', 'Know the location of the nearest first aid point and the identity of the on-site first aider or medical team before your shift begins — this will be confirmed during your site briefing. In a medical emergency, do not move an injured or unwell person unless they are in immediate danger; call for the on-site medical team or first aider immediately and stay with the person until help arrives. Only personnel with valid, current first aid certification may administer first aid beyond basic assistance. Every injury, however minor, must still be logged through the incident reporting process.'),
('emergency', 'en', 10, 'Emergency Procedures, Evacuation & Fire Safety', 'Every person on site must know the nearest emergency exit, evacuation route, and assembly point before the event or shift begins — this will be confirmed during your site briefing. In the event of an alarm or an instruction to evacuate, remain calm, assist patrons or colleagues where safe to do so, and proceed directly to the designated assembly point. Do not use lifts during an evacuation, and do not re-enter the venue until cleared by a fire marshal, safety officer, or emergency services.'),
('incident_reporting', 'en', 11, 'Incident, Hazard & Near-Miss Reporting', 'Every incident, injury, hazard, or near-miss — no matter how minor it may seem — must be reported to your supervisor immediately and logged before the end of your shift. Early reporting allows hazards to be corrected before they cause harm and is often a legal requirement in the country you are deployed in. Falsifying or withholding an incident report is a serious disciplinary matter.'),
('crowd_management', 'en', 12, 'Crowd Management & Public Safety', 'When managing crowds, prioritise calm, clear communication over confrontation. Watch for early warning signs of overcrowding, crushing, or crowd distress — such as pushing, restricted movement, or visible panic — and escalate to your supervisor immediately rather than attempting to resolve a developing crowd risk alone. Crowd safety is everyone''s responsibility on site, not only security personnel — anyone who spots a developing risk must raise it immediately. All interactions with the public, media, and talent must remain professional, patient, and non-confrontational at all times.'),
('access_control', 'en', 13, 'Access Control, Accreditation & Site Zoning', 'Access to any site is controlled by zone and accreditation level. You may only enter areas your accreditation authorises, and you must be able to produce it on request at any checkpoint. Unauthorised individuals attempting to access restricted, backstage, VIP, or technical zones must be politely but firmly redirected and reported to your supervisor or the Joint Operations Centre (JOC) where one is in place.'),
('use_of_force', 'en', 14, 'Use of Force, De-escalation & Search Procedures', 'De-escalation is always the first response. Physical intervention or use of force is a last resort, must be proportionate to the situation, and must comply with the laws of the country you are working in — these vary significantly between jurisdictions and it is your responsibility to know the local rules for your current deployment. Any search of a person or bag must follow the search procedure briefed for that specific site, must be conducted respectfully, and must be logged. Any use of force, however minor, must be reported the same shift.'),
('communication', 'en', 15, 'Communication Protocols & Chain of Command', 'Radios and communication devices must be used for operational communication only, kept on the assigned channel, and handled with proper radio discipline — clear, brief, and professional at all times. Know your direct supervisor and the reporting chain for your deployment before the shift begins. If you are unsure who to report something to, ask before the event starts, not during an incident.'),
('cultural_legal', 'en', 16, 'Cultural & Legal Compliance for International Deployment', 'You are responsible for respecting the local laws, customs, and cultural expectations of the country you are deployed in, which may differ from your home country and from other deployments you have worked. This includes local rules on dress standards, public conduct, photography and filming in public areas, and the handling of alcohol where applicable — some Gulf jurisdictions apply strict restrictions that do not exist elsewhere. Country-specific guidance will be provided as part of your deployment briefing; if anything is unclear, ask your supervisor before, not during, the assignment.'),
('data_protection', 'en', 17, 'Data Protection & Media Confidentiality', 'As Miraj Media personnel, you may have access to unreleased footage, talent movements, event schedules, or other confidential information. This information must not be shared, photographed, filmed, or discussed outside of your official duties, including on personal social media, at any time during or after the assignment. Any request from a third party for access to restricted areas, talent, or information must be referred to your supervisor and never granted independently.'),
('anti_bribery', 'en', 18, 'Anti-Bribery, Corruption & Zero-Tolerance Policy', 'Miraj Media and its personnel operate under a zero-tolerance policy on bribery and corruption in every country of deployment. You must never offer, accept, or facilitate a bribe, gift, or favour in exchange for preferential access, reduced scrutiny, or any other advantage — this applies to interactions with the public, other contractors, and officials alike. Any such approach made to you must be declined and reported to your supervisor immediately.')
on conflict do nothing;

-- Reminder: once you're happy with this English content, have the
-- Arabic/French/Swahili versions translated from THIS approved text
-- and insert them the same way with language = 'ar' / 'fr' / 'sw'.
